server: # 服务器元数据
  name: YA_MCPServer_Work
  name_zh: YA MCP 作业
  author: 韩轩,费郁诚
  description: not finished yet
  description_zh: 尚未完成
  version: 0.1.0

transport: # 服务器启动方式配置
  type: "sse" # 可选值: stdio, sse
  host: "0.0.0.0" # 仅在 type 为 sse 时有效，表示监听地址，默认为 0.0.0.0
  port: 12345 # 仅在 type 为 sse 时有效，表示监听端口，默认为 12345

logging: # 日志配置
  console:
    enabled: true
    level: "DEBUG"
  file:
    enabled: true
    level: "DEBUG"
    path: "logs/%Y-%m-%d_%H-%M-%S.log"
    rotation: "10 MB"
    retention: "7 days"
    compression: "zip"
